version: '3.2'
services:
  builder:
    volumes:
      - type: bind
        source: ./public
        target: /data/public
        read_only: false
    ports:
      - target: 1312
        published: 1312
        protocol: tcp
        mode: host
    image: isard/builder
    restart: unless-stopped
